### ISSUE TITLE
Add view to JavaFx application

### ISSUE THREAD

**Issue by Silfalion** [graphstream/gs-ui-javafx#12]
Hi everyone,

I'm raising this issue because I was trying to add a view to a JavaFx application with the following lines:

```
FxViewer fxViewer = new FxViewer(ind.tony, FxViewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
 fxViewer.addDefaultView(false);
```

but gives these error message:

```
Taches.xml
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: org/graphstream/ui/view/GraphRenderer
	at main.start(main.java:42)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	... 1 more
Caused by: java.lang.ClassNotFoundException: org.graphstream.ui.view.GraphRenderer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 10 more
Exception running application main
```

Here is my code:

```
import javafx.application.Application;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import org.graphstream.stream.file.FileSinkImages;
import org.graphstream.stream.file.FileSourceDGS;
import org.graphstream.ui.fx_viewer.FxViewer;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.ViewerPipe;
import org.jdom2.JDOMException;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

public class main extends Application {


    public static void main(String[] args) throws IOException, InterruptedException {



        launch(args);

    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        System.setProperty("org.graphstream.ui", "javafx");
        try {
            TaskManager.readXML();
        } catch (JDOMException e) {
            e.printStackTrace();
        }
        Individual ind = new Individual(10, 10);

        StackPane root = new StackPane();

        Viewer viewer = new Viewer(ind.tony, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.addDefaultView(false);
        FxViewer fxViewer = new FxViewer(ind.tony, FxViewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        fxViewer.addDefaultView(false);

        root.getChildren().add((Node) ind.tony);

        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    public void captureImage(Individual ind) throws IOException, InterruptedException {


        FileSinkImages pic = new FileSinkImages(FileSinkImages.OutputType.PNG, FileSinkImages.Resolutions.VGA);
        pic.setLayoutPolicy(FileSinkImages.LayoutPolicy.COMPUTED_FULLY_AT_NEW_IMAGE);
        pic.writeAll(ind.tony, "graph.png");

        ind.tony.display();


        FileSinkImages.OutputPolicy outputPolicy = FileSinkImages.OutputPolicy.BY_EVENT;
        String prefix = "prefix\\prefix_";
        FileSinkImages.OutputType type = FileSinkImages.OutputType.PNG;
        FileSinkImages.Resolution resolution = FileSinkImages.Resolutions.HD720;

        FileSinkImages fsi = new FileSinkImages( type, resolution );

        // Create the source

        FileSourceDGS dgs = new FileSourceDGS();

        // Optional configuration

        fsi.setStyleSheet(
                "graph { padding: 50px; fill-color: white; }" +
                        "node { fill-color: #3d5689; }" +
                        "edge { fill-color: black; }");

        fsi.setOutputPolicy( outputPolicy );
        fsi.setLayoutPolicy( FileSinkImages.LayoutPolicy.COMPUTED_FULLY_AT_NEW_IMAGE );
        fsi.setQuality(FileSinkImages.Quality.HIGH);

        // Images production

        dgs.addSink( fsi );

        fsi.begin(prefix);
        ind.tony.write("newDg.dgs");
        dgs.begin( "newDg.dgs" );
        while( dgs.nextStep() ){
            Thread.sleep(2000);
        }

        dgs.end();
        fsi.end();
       
    }
}
```

I'd like to know how to correct please, thanks for reading.

**Comment by hichbra** [comment]
Hi !

Remove this :
```java
Viewer viewer = new Viewer(ind.tony, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
viewer.addDefaultView(false);
```
After that, you need to create a Renderer and then you can get a FxDefaultView from the viewer to add to your Scene.
```java
FxViewer viewer = new FxViewer(graph, FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
GraphRenderer renderer = new FxGraphRenderer();
FxDefaultView view = (FxDefaultView) viewer.addView(FxViewer.DEFAULT_VIEW_ID, renderer);
```
You can see an example here : https://github.com/graphstream/gs-ui-javafx/blob/master/src-test/org/graphstream/ui/viewer_fx/test/AllFxTest.java
I invite you to take a look at the different examples: 
https://github.com/graphstream/gs-ui-javafx/tree/master/src-test/org/graphstream/ui/viewer_fx/test

**Comment by Silfalion** [comment]
Thank you bro for the examples!! I was looking for something like that.

However it didn't work for the program. it says 

The code had some problems with the renderer, so after trying and picking up from the example I arrived to this code: 

```

FxViewer viewer = new FxViewer(ind.tony, FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
FxViewPanel view = (FxViewPanel) viewer.addDefaultView(false, new FxGraphRenderer());
Scene scene = new Scene(view);

```

but it displays this error:

```

Taches.xml
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoSuchMethodError: org.graphstream.ui.view.Viewer: method <init>()V not found
	at org.graphstream.ui.fx_viewer.FxViewer.<init>(FxViewer.java:158)
	at main.start(main.java:44)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	... 1 more
Exception running application main

```

 I also tried running the example and it gives the same error. What should I do please?

Thanks again for taking the time to reply.

**Comment by hichbra** [comment]
Which version of gs-core and gs-ui-javafx are you using ?

**Comment by Silfalion** [comment]
Gs-core 2.0.0 and gs-ui-javafx 2.0 alpha.

**Comment by hichbra** [comment]
Your <version> tag must be the same, if you don't use maven please verify if you use the correct version. 
```xml
<dependency>
    <groupId>com.github.graphstream</groupId>
    <artifactId>gs-core</artifactId>
    <version>2.0-alpha</version>
</dependency>
<dependency>
    <groupId>com.github.graphstream</groupId>
    <artifactId>gs-ui-javafx</artifactId>
    <version>2.0-alpha</version>
</dependency>
```

**Comment by Silfalion** [comment]
Yep, the same. It gives me this error with the renderer:

```
Wrong 2nd argument type. 
Found: 'org.graphstream.ui.javafx.FxGraphRenderer', 
required: 'org.graphstream.ui.view.GraphRenderer<?,?>' 
addDefaultView (boolean, org.graphstream.ui.view.GraphRenderer<?,?>) in FxViewer cannot be applied to(boolean, org.graphstream.ui.javafx.FxGraphRenderer)
 
```

For this line: 

```

FxViewPanel panel = (FxViewPanel)v.addDefaultView(false, new FxGraphRenderer());

```

**Comment by hichbra** [comment]
In the code of your first post, you did :
```java
Viewer viewer = new Viewer(ind.tony, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
viewer.addDefaultView(false); 
```
But it's not possible with this version, because Viewer is now an abstract class as you can see here : 
https://github.com/graphstream/gs-core/blob/2.0-alpha/src/org/graphstream/ui/view/Viewer.java

Similarly, FxGraphRenderer is an implementation of GraphRenderer :
https://github.com/graphstream/gs-ui-javafx/blob/2.0-alpha/src/org/graphstream/ui/javafx/FxGraphRenderer.java

This is why I said  there's something wrong with your dependency, if you can create a new instance of Viewer that's mean you don't have a good version. Try to clean your dependencies and if you use maven, remove your home/.m2/repository/org/graphstream folder and update your project.

**Comment by Silfalion** [comment]
It worked *.*!! Thank you so much!! I deleted some folders on the m2 folder and used the latest gs-algo jar, just in case.

I know it might now be related so it's okay if you can't answer it.Tthough when the graph the nodes overlap their names and it's upside down with the Hierarchical layout. Would you a suggestion as how to fix that?

![capture d ecran 19](https://user-images.githubusercontent.com/23188369/39373209-2483cfc6-4a47-11e8-9736-068785807232.png)

Thank you soo much again.

**Comment by hichbra** [comment]
They just share the same color. You can change the color, move the text, add a padding / a background..., you have plenty of CSS properties to help you : http://graphstream-project.org/doc/Advanced-Concepts/GraphStream-CSS-Reference/
Good luck.

**Comment by Silfalion** [comment]
Thank you sooo much. You're awesome.

Have a great day:)

**Comment by kenc-921-dx-sp** [comment]
Thank you so much, this issue helps me to solve a very big problem for me.
Really, thank you so much.

**Comment by VersusF** [comment]
Hello.
I'm using this version of graphstream to incorporate a graph into a border pane with other informations. The problem is that when i show the stage i can't move the nodes with the mouse. Instead if I show the graph with `graph.display()` I can move them.

Here is my code:
```java
FXMLLoader loader = new FXMLLoader(getClass().getResource(CFG_VIEWER_PATH));
BorderPane root = loader.load();
mCfgViewerController = loader.getController();
FxViewPanel cfgView = cfg.getView();
root.setCenter(cfgView);
Stage stage = new Stage();
stage.setTitle(file.getName());
stage.setScene(new Scene(root));
stage.initModality(Modality.APPLICATION_MODAL);
stage.show();
```

where the function `getView` builds it like this
```java
// Graph creation skipped
mView = new FxViewer(mGraph, FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
mView.enableAutoLayout();
return (FxViewPanel) mView.addView(FxViewer.DEFAULT_VIEW_ID, new FxGraphRenderer());
```

Thanks for the help

**Comment by hichbra** [comment]
Hi !

Can you open a new issue in gs-ui-javafx ? I will answer it. Thanks you.
