### ISSUE TITLE
graph.setAttribute("ui.stylesheet", css) and FxViewer

### ISSUE THREAD

**Issue by kenc-921-dx-sp** [graphstream/gs-ui-javafx#17]
I have create a graph and set the css using graph.setAttribute("ui.stylesheet", css), and created a FxViewPanel. The graph is displayed properly, but it seems that the css is not working.

Code:
```
public static FxViewPanel createGraphPanel(Graph graph) throws MalformedURLException {
		String css = FXUtils.getCss(FXUtils.GRAPH_CSS_FILE_PATH);
                graph.setAttribute("ui.stylesheet", new URL(css));
		FxViewer viewer = new FxViewer(stateGraph, 
                FxViewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
		viewer.enableAutoLayout();
		FxViewPanel graphPanel = (FxViewPanel) viewer.addDefaultView(false, new FxGraphRenderer());
		return graphPanel;
	}
```

CSS:
```
graph {
	fill-color: red;
	fill-mode: plain;
	text-style:normal;
	text-mode:normal;
	text-background-mode:plain;
}

node {
	size: 10px;
	shape: circle ;
	fill-color: green;
	stroke-mode: plain;
	stroke-color: yellow;
}

node:clicked {
	fill-color: red;
}
```

Error:
```
Mar 13, 2019 10:50:42 PM org.graphstream.ui.graphicGraph.GraphicGraph attributeChanged
WARNING: Error with stylesheet specification what to do with 'file:/C:/Users/cfchiu6/git/awtu/resource/style/graph.css'.
```

**Comment by kenchiu21** [comment]
WARNING: Error while parsing style sheet for graph 'GraphicGraph_1029'.
java.io.IOException: Encountered " <IDENTIFIER> "file "" at line 1, column 1.
Was expecting one of:
    <EOF> 
    "graph" ...
    "edge" ...
    "node" ...
    "sprite" ...
    <COMMENT> ...
    
	at org.graphstream.ui.graphicGraph.stylesheet.StyleSheet.parse(StyleSheet.java:546)
	at org.graphstream.ui.graphicGraph.stylesheet.StyleSheet.parseFromString(StyleSheet.java:437)
	at org.graphstream.ui.graphicGraph.stylesheet.StyleSheet.load(StyleSheet.java:528)
	at org.graphstream.ui.graphicGraph.GraphicGraph.attributeChanged(GraphicGraph.java:471)
	at org.graphstream.graph.implementations.AbstractElement.setAttribute(AbstractElement.java:311)
	at org.graphstream.util.GraphListeners.graphAttributeAdded(GraphListeners.java:210)
	at org.graphstream.ui.graphicGraph.GraphicGraph.graphAttributeAdded(GraphicGraph.java:952)
	at org.graphstream.stream.SourceBase.sendAttributeChangedEvent(SourceBase.java:799)
	at org.graphstream.stream.SourceBase.sendGraphAttributeAdded(SourceBase.java:584)
	at org.graphstream.stream.thread.ThreadProxyPipe.processMessage(ThreadProxyPipe.java:523)
	at org.graphstream.stream.thread.ThreadProxyPipe.pump(ThreadProxyPipe.java:273)
	at org.graphstream.ui.fx_viewer.FxViewer.actionPerformed(FxViewer.java:279)
	at org.graphstream.ui.fx_viewer.FxViewer.lambda$init$0(FxViewer.java:195)
	at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at javafx.graphics/com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.graphics/javafx.animation.Timeline.doPlayTo(Timeline.java:177)
	at javafx.graphics/javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at javafx.graphics/com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.graphics/javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.graphics/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.animation.Animation$1.timePulse(Animation.java:185)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at javafx.graphics/com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kenchiu21** [comment]
WARNING: Error with stylesheet specification what to do with 'file:/C:/Users/cfchiu6/git/awtu/resource/style/graph.css'.

**Comment by pigne** [comment]
Pseudo-classes (`node:clicked`) are not supported in the css selectors. Only classes are (`node.clicked`). You can set a class in a node with attributes (`node.setAttribute("ui.class", "clicked")`).

**Comment by kenc-921-dx-sp** [comment]
> Pseudo-classes (`node:clicked`) are not supported in the css selectors. Only classes are (`node.clicked`). You can set a class in a node with attributes (`node.setAttribute("ui.class", "clicked")`).

Hi @pigne  , I have changed the css yet the same error message is shown T^T
